#Configuration file for all the scripts that work with the SQLite database
sqlite:
  name: insights
  storage_location:
  tables:
    Message:
      - type: string
      - date: date
      - time: time
      - sender: char
      - reciever: char
      - message: string
      - length: int
    Word:
      - word: char
      - length: int
      - occurences: int
    Call:
      - date: date
      - time: time
      - caller: char
      - reciever: char
      - length: double
      - answered: boolean
    Voicemail:
      - date: date
      - time: time
      - caller: char
      - message: string
    Contacts:
      - name: char
      - firstContact: date
      - lastContact: date
      - phoneNumbers: int
      - countryCode: string
      - lastNumber: int
    Locations:
      - date: date
      - time: time
      - longitude: double
      - latitude: double
      - continent: char
      - country: char
      - state: char
      - city: char
    Jobs:
      - title: char
      - company: char
      - description: string
      - startDate: date
      - endDate: date
      - type: string
      - currentlyWork: boolean
      - location: string
