#Configuration file for all the scripts that work with the SQLite database
sqlite:
  name: insights
  dbType: sqlite #Choices are: sqlite, extended, apsw
  storage_location:
  tables:
    message:
        type: string
        date: date
        time: time
        sender: char
        reciever: char
        message: string
        length: int
    word:
        word: char
        length: int
        occurences: int
    call:
        date: date
        time: time
        caller: char
        reciever: char
        length: double
        answered: boolean
    voicemail:
        date: date
        time: time
        caller: char
        message: string
    contacts:
        name: char
        firstContact: date
        lastContact: date
        lastMessage: string
        phoneNumbers: int
        countryCode: string
        lastNumber: int
    locations:
        date: date
        time: time
        longitude: double
        latitude: double
        continent: char
        country: char
        state: char
        zip: int
        city: char
        street: string
        name: string
    jobs:
        title: char
        company: char
        description: string
        startDate: date
        endDate: date
        type: string
        currentlyWork: boolean
        location: string
    socialmedia: #Used for current news, etc. around other events, such as twitter posts at a specific time
        type: char
        date: date
        time: time
        message: string
        tags: string
        urls: string
    photos:
        name: char
        date: date
        time: time
        location: string
        shutter: string
        iso: int
        shotFormat: string
        aperture: string
        manufacturer: char
        cameraModel: char
        exposurePriority: string
        exposureMode: string
        flash: boolean
        lensModel: string
        focalLength: double
        service: string
        dateUpload: date
    calendar:
        startDate: date
        startTime: time
        finishDate: date
        finishTime: time
        type: char
        whichCalender: char
        description: string
        name: string
        duration: double
        isTask: boolean