#Configuration file for all the scripts that work with the SQLite database
sqlite:
  name: insights
  storage_location:
  tables:
    Message:
      - type: string
      - date: date
      - time: time
      - sender: string
      - reciever: string
      - message: string
      - length: int
    Word:
      - word: string
      - length: int
      - occurences: int
    Call:
      - date: date
      - time: time
      - caller: string
      - reciever: string
      - length: double
      - answered: boolean
    Voicemail:
      - date: date
      - time: time
      - caller: string
      - message: string
    Contacts:
      - name: string
      - firstContact: date
      - lastContact: date
      - phoneNumbers: string
      - countryCode: string
      - lastNumber: string
    Locations:
      - date: date
      - time: time
      - longitude: double
      - latitude: double
      - continent: string
      - country: string
      - state: string
      - city: string
    Jobs:
      - title: string
      - company: string
      - description: string
      - startDate: date
      - endDate: date
      - type: string
      - currentlyWork: boolean
      - location: string
